DROP FUNCTION IF EXISTS CHECKUSER;
DELIMITER //

CREATE FUNCTION CHECKUSER(EMAIL_TO_VALIDATE VARCHAR(50), PASSWORD_TO_VALIDATE TEXT)
RETURNS TINYINT
BEGIN
  DECLARE RESULT TINYINT;
  DECLARE VIRTUALPASSWORD VARCHAR(128);
  DECLARE VIRTUALSALT TEXT;

  IF EMAIL_TO_VALIDATE IS NULL OR PASSWORD_TO_VALIDATE IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'EMAIL OR PASSWORD CANNOT BE NULL';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = EMAIL_TO_VALIDATE) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = CONCAT('NO USER FOUND WITH THE EMAIL : ', EMAIL_TO_VALIDATE);
  END IF;

  SELECT SALT, HASH_PASSWORD
  INTO VIRTUALSALT, VIRTUALPASSWORD
  FROM USERS
  WHERE EMAIL = EMAIL_TO_VALIDATE;

  IF VIRTUALPASSWORD = HASHEDPASSWORD(CONCAT(VIRTUALSALT, PASSWORD_TO_VALIDATE)) THEN
    SET RESULT = 1; -- True
  ELSE
    SET RESULT = 0; -- False
  END IF;

  RETURN RESULT;
END //
